### ISSUE TITLE
Looking for sourceutil.js sourcecode

### ISSUE THREAD

**Issue by jonahbearde** [Facepunch/Facepunch.WebGame#1]
Hi there! I'm sorry this is not issue related, but I noticed that after the maps are exported, there's another js file called `sourceutil.js` in the resource folder, reading the build artifact directly is hard for me, so I want to know if you have a repo about this library, i would greatly appreciate it if you share the sourcecode and it's fine if you don't want to.

**Comment by Metapyziks** [comment]
I think the source for that is here: 

https://github.com/Metapyziks/SourceUtils/tree/master/SourceUtils.WebExport/Resources/src

Hope that helps!

**Comment by jonahbearde** [comment]
thanks a lot
